### ISSUE TITLE
Label interpreration does not work in some cases

### ISSUE THREAD

**Issue by soramichi** [ruechip/kuechip-assembler#1]
When a label is used for the operand of a Bcc instruction, it is evaluated as a NAN when the label follows some conditions.

I have not yet fully understood how this happens, but here are some guesses:
- A label should not start with mnemonics of other instructions? (Case 1 and 2, but what about Case 4??)
- A label should not end with 'H' as it may be confused as a hex number? (Case 1 vs. Case 3)

### Non-working cases
Case 1:
```
0000: 0030 0NAN  # BA ENDH
0004: 00C9       # ENDH: EOR IX IX
```

Case 2:
```
0000: 0030 0NAN  # BA SUBH
0004: 00C9       # SUBH: EOR IX IX
```

### Working cases
Case 3:
```
0000: 0030 0004  # BA ENDA
0004: 00C9       # ENDA: EOR IX IX
```

Case 4:
```
0000: 0030 0004  # BA CMPH
0004: 00C9       # CMPH: EOR IX IX
```

**Comment by ruechip** [comment]
A Label is not converted correctly when ends in the character [0-9A-Fa-f][Hh].
Please don't use Labels as follows,
    "x0H" "x9h" "yAH" "yFh" "zaH" "zfh"
 for a while.
